services:
  amd64:
    image: smasherofallthings/backup:amd64-${Tag:-latest}
    build:
      context: '.'
      dockerfile: Dockerfile
      no_cache: true
      pull: true
      args:
        BaseImage: smasherofallthings/base-image:amd64-latest
      platforms:
        - "linux/amd64"
